### ISSUE TITLE
Cannot clone the mRNA sequence

### ISSUE THREAD

**Issue by RishabSwift** [NAalytics/Assemblies-of-putative-SARS-CoV2-spike-encoding-mRNA-sequences-for-vaccines-BNT-162b2-and-mRNA-1273#6]
Hello, 

My first step was downloading the PDF.

Now, I have no idea what to do. Can someone tell me what's step 2?

How do I make my own vaccine out of this? 

Thanks

**Comment by ricktm** [comment]
i'd start here: https://www.the-odin.com

**Comment by NAalytics** [comment]
I am sure this is just a joke, but just in case it is a serious thread, no, you cannot clone this mRNA sequence and neither should you. 

**1-** it is incomplete
**2-** a vaccine contains many more elements than just the mRNA (and it is way more complex). It is important to note that constructing an RNA-vaccine requires much more information and many steps of synthesis and formulation in addition to an RNA sequence (there is a complex formulation involving encapsulation, synthetic chemistry, enzymology and lipid/membrane dynamics that are additional requirements for making a vaccine). The scientists doing this for Moderna/NIH and BioNTech/Pfizer have done a great service and have successfully optimized a protocol that is built on many thousands of person-years of science (chemistry, molecular biology, bioinformatics, pharmacology, and a few more "ologies' we can't even spell) to deliver a vaccine that is both safe and effective. 
**3-** the RNA is likely to be modified, we don't capture those modifications in our analysis
**4-** our analysis is meant to provide value to the community in several ways (none of which include making your own RNA).  Here are two examples (one related to research into understanding how viruses work and one related to designing better clinical tools [in this case diagnostic])
(i) Next Generation Sequencing studies, like the ones used in our work, are designed to pick up low signals (i.e. able to extract information or “reads” from very low amounts of DNA or RNA in the environment). Thus, (as noted above) these sequences will be encountered in numerous sequencing studies (clinical or otherwise)-- and already have in several places.  While anyone interested could data-mine and filter these sequences out later, there is a substantial economy of scale (and educational value) in having the sequences available ASAP and in not having to guess where they have come from.  As an example, any medical or public health analysis relying on high throughput sequencing data to track SARS-COV2 and its variants would benefit from knowing the vaccine sequence in order to distinguish reads from the vaccine RNAs from RNAs of viral origin. 
(ii) Diagnostic labs designing nucleic acid surveillance tests (like PCR or LAMP assays) have a substantial need to know the vaccine sequences so that there is no confusion once an assay has been developed between a person that has been vaccinated and a person infected with the virus.

**Comment by coolreader18** [comment]
@NAalytics that's a really great explanation of what this repository/writeup is, you should put that in the readme or something like that.

**Comment by NAalytics** [comment]
@coolreader18 Thanks. Will do.
